databases:
  - name: minion
    databaseName: minion
    user: minion_user

services:
  - type: web
    name: minion
    env: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: minion
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
