default: &default
  adapter: postgresql
  encoding: unicode
  # user: postgres
  # host: localhost
  # password: brian
  # port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: minion_api_development

test:
  <<: *default
  database: minion_api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
